import { useState, useEffect } from "react";
import Head from "next/head";
import AppLayout from "../components/appLayout";
import Button from "../components/button";
import GitHub from "../components/icon/github";
import { colors } from "../styles/theme";
import { loginWithGithub, onAuthStateChanged } from "../firebase/client";
export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChanged((user) => {
      console.log(user);
      setUser(user);
    });
  }, []);

  const handleClick = () => {
    loginWithGithub()
      .then((user) => {
        const { avatar, userName, email } = user;
        setUser(user);
        console.log(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/devter-logo.png" alt="logo" />
          <h1>Devter</h1>
          <h2>Talk about development with developers</h2>
          <div>
            {user === null ? (
              <Button onClick={handleClick}>
                <GitHub width={24} height={24} fill="#fff" />
                Login with Github
              </Button>
            ) : (
              <div>
                <img src={user.avatar} alt="avatar" />
                <strong>{user.userName}</strong>
              </div>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>
        {`
          div {
            margin-top: 16px;
          }
          section {
            display: grid;
            height: 100%;
            place-items: center;
            place-content: center;
          }

          img {
            width: 100px;
          }

          h1 {
            color: ${colors.primary};
            font-size: 24px;
            font-weight: 800;
            margin-bottom: 0;
          }

          h2 {
            color: ${colors.secondary};
            font-size: 18px;
          }
        `}
      </style>
    </>
  );
}
